### ISSUE TITLE
変換ソースのHTMLにすでにstyle属性がある時の挙動について

### ISSUE THREAD

**Issue by oti** [hail2u/node-inlining#2]
外部CSS側で指定したプロパティーと同じプロパティーがHTML側のstyle属性ですでに指定されていると、外部CSS側で指定されたものが既存のstyle属性に追記されるという現在の仕様により、変換前と変換後でブラウザの表示結果が異なってしまう現象を確認しました。

以下再現ソースです。

test.html↓

```
<!DOCTYPE html>
<html lang="jp">
<head>
    <meta charset="UTF-8">
    <title>test</title>
    <link rel="stylesheet" href="test.css">
</head>
<body>
    <h1 style="color: red;">Document Heading</h1>
</body>
</html>
```

test.css↓

```
h1{
    color: blue;
}
```

```
$ inlining test.html >test.min.html
```

test.min.html↓

```
<!DOCTYPE html><html lang="jp"><head>
    <meta charset="UTF-8">
    <title>test</title>

</head>
<body>
    <h1 style="color: red;color:blue;">Document Heading</h1>

</body></html>
```

同じプロパティがstyle属性ですでに記述されていたら、外部CSSソース側の指定を無視して残りの宣言をコピーする、というのが理想ですが、そういった仕様変更は可能でしょうか？

**Comment by hail2u** [comment]
jsdom(かその依存ライブラリー)の仕様で、`Element.style`経由で操作しようとするとどうもうまくいかないプロパティーが出てくる。そのため上書きされるかどうかを確認しつつ……というのが少し難しそう。またそのやり方だとショートハンド・プロパティーの扱いもまた難しそうな感じがする。

元の`style`属性を保存しておいて、最後に改めて`style`属性の最後に追加する形で、擬似的に詳細度を再現するようにしてみる。

**Comment by oti** [comment]
修正を確認しました。
ありがとうございました！
